### ISSUE TITLE
Error when importing module in Powershell

### ISSUE THREAD

**Issue by SimonRousingBerg** [abbgrade/PsMermaidTools#1]
**PS Version**
Name                           Value
----                           -----
PSVersion                      5.1.19041.3930
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3930
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Module Version**
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.5.0      PsMermaidTools

**Error**
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:404 char:44
+                             '' { "$( $Text ? "[$Text]" : '' )" }
+                                            ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:405 char:52
+                             rectangle { "[$( $Text ? $Text : $Key )]" ...
+                                                    ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:406 char:54
+                             round-edges { "($( $Text ? $Text : $Key ) ...
+                                                      ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:407 char:51
+                             stadium { "([$( $Text ? $Text : $Key )])" ...
+                                                   ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:408 char:54
+                             subroutine { "[[$( $Text ? $Text : $Key ) ...
+                                                      ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:409 char:55
+                             cylindrical { "[($( $Text ? $Text : $Key  ...
+                                                       ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:410 char:50
+                             circle { "(($( $Text ? $Text : $Key )))"  ...
+                                                  ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:411 char:53
+                             asymmetric { ">$( $Text ? $Text : $Key )] ...
+                                                     ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:412 char:50
+                             rhombus { "{$( $Text ? $Text : $Key )}" }
+                                                  ~
Unexpected token '?' in expression or statement.
At C:\Users\<MySecretUsername>\OneDrive\Documents\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\Public\ConvertTo-String.ps1:413 char:51
+                             hexagon { "{{$( $Text ? $Text : $Key )}}" ...
+                                                   ~
Unexpected token '?' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
Import-Module : The module to process 'PsMermaidTools.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Users\<MySecretUsername>\OneDrive\Do
cuments\WindowsPowerShell\Modules\PsMermaidTools\0.5.0\PsMermaidTools.psd1' was not processed because no valid module was found in any module directory.
At line:22 char:13
+             Import-Module -Name $module
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (PsMermaidTools:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by abbgrade** [comment]
Thanks for reporting that issue. I did not test it with Powershell 5 but only 7 and newer. I need to check how much effort it is to fix it, or If I need to drop support of that old version. Maybe it is an option for you to upgrade.

**Comment by SimonRousingBerg** [comment]
I installed powershell 7.4.1 and it works like a charm.

Maybe you could either fix the issue or add what min. version is required for the module?

The easy workaround is for the user to install the latest version of PowerShell and for you just to set the PowerShellVersion in this section inside the module manifest.

```
# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'
```
