### ISSUE TITLE
ConvertTo-MermaidString cmdlet does not exists

### ISSUE THREAD

**Issue by SimonRousingBerg** [abbgrade/PsMermaidTools#2]
Hi

Based on you function under src/public/ConvertTo-String.ps1

The actual function name is wrong based on the example documentation.
I would expect it to be named ConvertTo-MermaidString right?

https://github.com/abbgrade/PsMermaidTools/blob/main/src/Public/ConvertTo-String.ps1

**Comment by abbgrade** [comment]
Mermaid is configured as default prefix in the module manifest. It's correct as it is. But thanks anyway fir reporting.

**Comment by SimonRousingBerg** [comment]
Ah, thanks.
